language: android
jdk: oraclejdk8
android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
install: true
before_script:
  - touch local.properties
script: ./gradlew build test
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
deploy:
  - provider: releases
    api_key:
      secure: ZCohn/1PZPvQ26LtO9v1FVsaEaDWf/T5xI5CuflcqJHGwOOUs8qAauwPbQbcjx5YBmzlqdp3bU1OVZaBy2aygHXxGkzUIEnmhcE6xJXWOUNBA7sVAKr4C7KaMtwsogc0e9lxGPJFvA6gfV23JS5HXmyz9uBrDMIHO1ezL9Wc1uiugyTCfQ/FtCn6gOfdJ3znjhnkCepcHJKxBB69cYDyOgzoKZ8Ilq7kIAdk/MFWP4a9cEZrUek9mF2NE4Si2nGJ4/VpivzJmhTo3cznE09YWXK/uMadQWPPqi8n5EuTmbyC18OzyIAB+Vmd8iD7uwByqmlVNZQeHsLxmdzg+3XvnTRFANtvQy5Ka2io1bWRcRdkqkcAssU2nptt41ju9t2I2Zolh4U2d5F3zziry+mjiwl/4aB0NMxW8oC8HwUBJmtlxQGF2dBfNNhHXctJibUfyGCqP/yho0LnBtsBF6uaaZ78wsqr5ZVxbafMSkGGOLZmNroGq33wUDoRYfg8UGsCh0JGbLEVR1LuuZve7vxBUqT4Wwju5c7sZbYDK81u1DJYouBujqkJqwh4E71J6wgvRiK7wzV42RpnWxzxpUZTtbSL8GqfAYadB2pRFLBK2LjsLiO+hQrZjQQXWLEcld3jhpK1R/RviBSs3hkMmAZCWyY6kdiK3Mt83OKZ3y/Hwv4=
    file: apk
    skip_cleanup: true
    on:
      repo: bleeding182/auth
      tags: true
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      tags: true
env:
  global:
    secure: po60jGS/pxiTpTcQ53TwZHqTYYf9G3oCIDzoocSOI3ObhvUdky7+ZU0BaTEW8soTk2VpCmrpysK/597SkUJaZZSFTXHcmQpvrDO/wnnLrquETXlZHoQ22MgErV6fZwTGo9VRjhnihcfIcS5mWkVnCOWZL1+TWf5Lz+2R2dcY7wVBLjigQKFe3QzdMDIf6DvLmQj/TpqnJTsXr+Ok1qMIa2vE8b1tobgA85wsZgZqIf2CccF7ixbTPjODwx91VI0Z0Hx8g2kdOMMDFZSN4A/ZY4OtQo7hfm9e1t3CLHO1eN4ojj+WJArOiBh2IHKJRanan8JJ0GbR67bWWa0m01VY90AZZHHyy4iKYwZFNMZWrZCtng2+kE17/QMAmESts/rjboAgNRLOc3N80gQH6cJTvnyFvwbYkTypXgxo8T48GX0fY6MJ+64zKOipB/tfxXxX4L8kwlegD6m38+kKhwdHlmKVVp0jt3noyIdLv8F1IaNw0Dc273nJ3BYYUbhHKRKXcn5Ch5A2hwi+otPMHaCRZVeQZTrSUogrmM3Q6b5DcMkUZqwxuQj4Ave/qXAA+VbbmLUH5MwNpf+T+JN3uQeRg+knc41TjL46KDJCNSFdDcPKa3G8GoMCjl47PQdgqBN6+oOEmeQcdyGrA7ntRoQ2wUU6qnGQk1w2R6GAoeDDSEY=
